baseURL = "/"
languageCode = "zh-cn"
title = "Laojianzi Read Notes"

theme = "book"
disablePathToLower = true
enableGitInfo = true
disqusShortname = "Laojianzi"

[params]
    BookRepo = "https://github.com/laojianzi/read-notes"
